# Executed ONLY as a fixture generated by cfg(test). MODE and ROOT are injected.
import json
import os
from pathlib import Path
import subprocess
import sys
import time

root = Path(ROOT)
counts = {'create':0,'resume':0,'detach':0,'abort':0,'send':0,'permissions_denied':0,'hooks_denied':0,'empty_hook_outputs':0}

def save():
    (root/'counts.json').write_text(json.dumps(counts))

def emit(value):
    body=json.dumps(value).encode()
    sys.stdout.buffer.write(b'Content-Length: '+str(len(body)).encode()+b'\r\n\r\n'+body)
    sys.stdout.buffer.flush()

def event(sid,kind):
    emit({'jsonrpc':'2.0','method':'session.event','params':{'sessionId':sid,'event':{
        'id':str(time.monotonic_ns()),'parentId':None,'timestamp':'2026-10-10T00:00:00Z',
        'type':kind,'data':{'content':'fixture-private-reasoning-and-credential'}}}})

if MODE=='descendant':
    p=subprocess.Popen(['/usr/bin/python3','-c','import os,time;os.setsid();time.sleep(120)'],stdin=subprocess.DEVNULL,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    (root/'descendant.pid').write_text(str(p.pid))

while True:
    headers={}
    while True:
        line=sys.stdin.buffer.readline()
        if not line:
            save()
            if MODE=='hung_exit':time.sleep(120)
            sys.exit(0)
        if line in (b'\r\n',b'\n'): break
        k,v=line.decode().split(':',1);headers[k.lower()]=v.strip()
    request=json.loads(sys.stdin.buffer.read(int(headers['content-length'])))
    if 'method' not in request:
        if request.get('id')==900000:
            output=request.get('result',{}).get('output',{})
            if output.get('permissionDecision')=='deny': counts['hooks_denied']+=1
            elif MODE=='malformed_hook' and output=={}: counts['empty_hook_outputs']+=1
            else: (root/'unapproved-effect').write_text('hook bypass')
            save()
        if request.get('id')=='permission-probe':
            assert 'denied' in json.dumps(request).lower()
            counts['permissions_denied']+=1;save()
        continue
    if 'id' not in request: continue
    method=request['method'];params=request.get('params') or {}
    result={'success':True}
    if method in ('connect','ping'):
        result={'ok':True,'version':'1.0.95','protocolVersion':3,'timestamp':1}
        if MODE=='startup_death': save();os._exit(13)
    elif method=='status.get': result={'version':'incompatible' if MODE=='incompatible' else '1.0.95','protocolVersion':3}
    elif method in ('session.create','session.resume'):
        counts['create' if method=='session.create' else 'resume']+=1
        assert params.get('availableTools')==[]
        assert params.get('mcpServers')=={}
        assert params.get('requestPermission') is True
        assert params.get('hooks') is True
        for name in ('enableSkills','enableConfigDiscovery','enableHostGitOperations','enableOnDemandInstructionDiscovery','requestExtensions','requestMcpApps'):
            assert params.get(name) is False,(name,params.get(name))
        assert str(params.get('configDir')).endswith('/session-state')
        save()
        if MODE=='session_death':os._exit(13)
        if MODE=='resume_missing' and method=='session.resume':
            emit({'jsonrpc':'2.0','id':request['id'],'error':{'code':-32000,'message':'Session not found fixture-private-secret'}});continue
        if MODE=='create_error':
            emit({'jsonrpc':'2.0','id':request['id'],'error':{'code':-32603,'message':'fixture-private-secret'}});continue
        if MODE=='slow':time.sleep(.15)
        result={'sessionId':params['sessionId'],'workspacePath':params['workingDirectory']}
    elif method=='session.getMessages':
        result={'events':[{'id':'fixture-other-root' if MODE=='history_mismatch' and counts['resume'] else 'fixture-root','parentId':None,'timestamp':'2026-10-10T00:00:00Z','type':'session.start','data':{}}]}
    elif method=='session.options.update':
        assert params.get('skipCustomInstructions') is True
    elif method=='session.permissions.handlePendingPermissionRequest':
        assert params['result']['kind']=='reject'
        counts['permissions_denied']+=1
    elif method=='session.abort':counts['abort']+=1
    elif method=='session.detach':counts['detach']+=1
    elif method=='session.send':
        counts['send']+=1;save();raise AssertionError('LR10B cannot send')
    elif method not in ('session.options.update','runtime.shutdown','session.skills.reload'):
        emit({'jsonrpc':'2.0','id':request['id'],'error':{'code':-32601,'message':'fixture-private-secret'}});continue
    if method=='session.options.update':
        if MODE=='tools':event(params['sessionId'],'tool.execution_start')
        elif MODE=='error_event':event(params['sessionId'],'session.error')
        elif MODE=='burst':
            for _ in range(400):event(params['sessionId'],'assistant.reasoning')
        elif MODE=='permission':
            emit({'jsonrpc':'2.0','method':'session.event','params':{'sessionId':params['sessionId'],'event':{
                'id':'permission-event','parentId':None,'timestamp':'2026-10-10T00:00:00Z','type':'permission.requested',
                'data':{'sessionId':params['sessionId'],'requestId':'permission-probe','permissionRequest':{'kind':'shell','fullCommandText':'echo forbidden'}}}}})
        elif MODE in ('hook','malformed_hook'):
            input={'sessionId':params['sessionId'],'timestamp':1,'cwd':params.get('workingDirectory','/tmp'),'toolName':'bash','toolArgs':{'command':'fixture private secret'}}
            if MODE=='malformed_hook': input={'toolName':'bash'}
            emit({'jsonrpc':'2.0','id':900000,'method':'hooks.invoke','params':{'sessionId':params['sessionId'],'hookType':'preToolUse','input':input}})
    emit({'jsonrpc':'2.0','id':request['id'],'result':result})
    save()
