#!/usr/bin/env python3
"""LR-9E: independent handler, AppManifest, ACL and production-bundle assertions."""
import argparse,json,re,subprocess
from pathlib import Path
parser=argparse.ArgumentParser();parser.add_argument('--output');parser.add_argument('--bundle',action='store_true');args=parser.parse_args()
base='d11d5834aacaa97bf642a24e6aeee7e1628c4617'
forbidden={'start_mock_task','start_mock_cognition_task','cognition_provider_status','security_test_store_secret','security_test_delete_secret','lr4_status','lr4_import_private_bootstrap','lr4_create_diagnostic_conversation','lr4_get_recent_conversation','perf1c_ui_report'}
def dev_only(command):return command in forbidden or bool(re.search(r'^(security_test_|lr4_|start_mock_|perf.*_ui_report)',command))
def read(path,old=False):return subprocess.check_output(['git','show',f'{base}:{path}'],text=True) if old else Path(path).read_text()
def inventory(old=False,profile='release'):
 condition='not(debug_assertions)' if profile=='release' else 'debug_assertions'
 s=read('src-tauri/src/lib.rs',old).split('#[cfg('+condition+')]\n    let builder = builder.invoke_handler',1)[1].split(']);',1)[0]
 # Opt-in report is compiled only with the explicitly instrumented probe feature.
 s=re.sub(r'#\[cfg\(feature = "perf1c-probe"\)\]\s*perf1c_probe::perf1c_ui_report,','',s)
 handler={m.group(0).split('::')[-1] for m in re.finditer(r'\b(?:\w+::)+\w+\b',s.split('tauri::generate_handler![',1)[1])}
 s=read('src-tauri/build.rs',old).split('#[cfg('+condition+')]',1)[1].split('];',1)[0]
 manifest=set(re.findall(r'"([a-z0-9_]+)"',s))
 acl=json.loads(read('src-tauri/capabilities/main-window.json',old))['permissions']
 all_commands=handler|manifest|forbidden
 caps=[json.loads(read(str(p),old)) for p in Path('src-tauri/capabilities').glob('*.json')]
 all_commands|={p.removeprefix('allow-').replace('-','_') for cap in caps for p in cap['permissions'] if p.startswith('allow-')}
 # Definition files are known to the ACL manifest even without permission grants.
 # They remain useful to debug builds and must not be reported as release access.
 definitions={p.stem for p in Path('src-tauri/permissions/autogenerated').glob('*.toml')}
 if old:definitions={Path(p).stem for p in subprocess.check_output(['git','ls-tree','-r','--name-only',base,'--','src-tauri/permissions/autogenerated/'],text=True).splitlines() if p.endswith('.toml')}
 return [{'command':c,'handler':c in handler,'appManifestDeclared':c in manifest,'appManifestKnownPermissionDefinition':c in definitions,'capability':'allow-'+c.replace('_','-') in acl,'capabilityWindows':[w for cap in caps if 'allow-'+c.replace('_','-') in cap['permissions'] for w in cap['windows']],'devOnly':dev_only(c),'purpose':'DEV/fixture' if dev_only(c) else 'product','frontendConsumers':[str(p) for p in Path('src').rglob('*') if p.suffix in ('.ts','.tsx') and c in p.read_text()]} for c in sorted(all_commands)]
# LR-9D cognitive inputs/schemas remain identical to this phase's approved base.
def function(source,name):
 start=source.index(f'fn {name}(');return source[start:source.index('\n}',start)+2]
contracts={
 'src-tauri/src/luna/runtime.rs':['chat_budget_and_request'],
 'src-tauri/src/cognition/summary.rs':['summary_request','summary_input'],
 'src-tauri/src/cognition/orchestrator.rs':['model_contract','task_graph_model_contract','request','task_graph_request','request_with_contract'],
 'src-tauri/src/cognition/task_graph_worker.rs':['worker_input','worker_system_instruction'],
 'src-tauri/src/agents/codex/backend.rs':['thread_config','thread_start_params','turn_start_params','production_config','inspect_notification','inspect_notification_mode'],
 'src-tauri/src/agents/planner.rs':['output_schema']}
for path,names in contracts.items():
 for name in names:assert function(read(path,True),name)==function(read(path),name),(path,name)
for path in ['src-tauri/Cargo.lock','package.json','package-lock.json','src-tauri/src/cognition/types.rs','src-tauri/src/agents/types.rs']:
 assert read(path,True)==read(path),('dependency/request contract',path)
assert not subprocess.check_output(['git','diff','--name-only',base,'--','src-tauri/migrations/'],text=True).strip()
rows=inventory()
assert {r['command'] for r in rows if r['handler']}=={r['command'] for r in rows if r['appManifestDeclared']}, 'release handler/AppManifest mismatch'
for r in rows:
 if r['devOnly']:assert not any(r[k] for k in ('handler','appManifestDeclared','capability')),r
build=read('src-tauri/build.rs');assert re.findall(r'commands\.push\("([a-z0-9_]+)"\)',build)==['perf1c_ui_report']
assert 'if std::env::var_os("CARGO_FEATURE_PERF1C_PROBE").is_some() {\n    commands.push("perf1c_ui_report");' in build
for cap in Path('src-tauri/capabilities').glob('*.json'):
 c=json.loads(cap.read_text());assert 'remote' not in c
 for p in c['permissions']:
  assert not any(p.startswith(x) for x in ('shell:','fs:','process:','stronghold:')),p
  assert p not in {'allow-'+x.replace('_','-') for x in forbidden},p
  if p.startswith('allow-'):assert not dev_only(p.removeprefix('allow-').replace('-','_')),p
  if cap.stem.startswith('settings-'):assert not any(x in p for x in ('human-terminal','terminal-input','terminal-surface','terminal-activity','resize-terminal','diagnostic','mock','lr4-','security-test')),p
c=json.loads(Path('src-tauri/debug-diagnostics.json').read_text());assert c['windows']==['main'] and 'remote' not in c
assert set(c['permissions'])=={'allow-'+x.replace('_','-') for x in forbidden-{'perf1c_ui_report'}}
debug_rows=inventory(profile='debug')
for row in debug_rows:
 row['debugDynamicMainCapability']=row['command'] in forbidden-{'perf1c_ui_report'}
 if row['command'] in forbidden-{'perf1c_ui_report'}:assert row['handler'] and row['appManifestDeclared'] and row['debugDynamicMainCapability'],row
s=Path('src-tauri/src/lib.rs').read_text();assert '#[cfg(debug_assertions)]\n            app.add_capability(include_str!("../debug-diagnostics.json"))?' in s
conf=json.loads(Path('src-tauri/tauri.conf.json').read_text());csp=conf['app']['security']['csp'];assert csp['script-src']=="'self'" and csp['style-src']=="'self'"
assert csp['frame-src']=="'none'" and csp['worker-src']=="'none'"
assert 'execute_command' not in s
contract=Path('src-tauri/src/execution/contract.rs').read_text()
for name in ('ExecutionAuthority','ExecutionRequest','ExecutionResult'):
 assert not re.search(r'#\[derive\([^\]]*(?:Serialize|Deserialize)[^\]]*\)\]\s*pub struct '+name,contract)
if args.bundle:
 bundle='\n'.join(p.read_text() for p in Path('dist').rglob('*.js'))
 for c in forbidden:assert c not in bundle,('production bundle',c)
result={'pass':True,'base':base,'before':inventory(True),'after':rows,'debugAfter':debug_rows,'debugDynamicMainOnly':True,'settingsIsolated':True,'productionCspUnchanged':True,'bundleChecked':args.bundle}
resolved=Path('src-tauri/gen/schemas/capabilities.json')
if resolved.exists():
 generated=json.loads(resolved.read_text())
 for cap in generated.values():
  assert not set(cap['permissions']) & {'allow-'+x.replace('_','-') for x in forbidden},cap
 assert 'debug-diagnostics-only' not in generated
 result['resolvedStaticCapabilitiesChecked']=True
else:result['resolvedStaticCapabilitiesChecked']=False
manifest_path=Path('src-tauri/gen/schemas/acl-manifests.json')
if manifest_path.exists():
 app_acl=json.loads(manifest_path.read_text())['__app-acl__']
 known={c for p in app_acl['permissions'].values() for c in p['commands']['allow']}
 for row in rows:assert row['appManifestKnownPermissionDefinition']==(row['command'] in known),row
 result['generatedAclManifestKnownDefinitionsChecked']=True
 result['knownDefinitionsAreNotReleaseGrants']=True
if args.output:Path(args.output).write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n')
print('LR-9E release: handler / AppManifest / static capability separated; DEV ACL debug-only main; settings isolated; no generic exec; bundle='+str(args.bundle))
